### PR TITLE
Updating build system and font sources

### PR DESCRIPTION
**Pull request by aaronbell**
Updated the build system to use GF's standard builder tool. Also updated font sources to address font bakery bugs.

### CODE REVIEW

**Comment by hfhchan** [comment]
The first commit is so large github refuses to generate a preview :/

The original author doesn't have glyphs, so whenever he makes a change and re-export the UFO from the `.fcp` file he is using, all of the changes made to the .UFO files will be overwritten. He knows nothing about software engineering. The best we could do was to guide him on exporting a .UFO file from Font Creator, and then committing the changes through GitHub Desktop.

Any changes made to the .UFO font files needs to be done as part of the build phase and shouldn't be committed back to the repository.

I'm not familiar enough with python to have done that, so I did it in JavaScript. The alternative is updating fontbakery to support the (mildly corrupted) .UFO files Font Creator generates.

**Comment by hfhchan** [comment]
Since GitHub refuses to generate previews, my review has to go here:

`The Caactus Classical Serif Project Authors` should be `The Cactus Classical Serif Project Authors`.

Authors does not have Adobe in it because the font does not have anything from Adobe.

Authors should be the following:
- 田海東 @jisbig5
- 宇文滿月 @MoonlitOwen
- Henry Chan @hfhchan

There are also glyphs in this font which are derived from other projects, do we include them as part of authors?

Thanks for your advice.

**Comment by aaronbell** [comment]
Oh! I thought I'd read somewhere that this included glyphs from an Adobe project. I can remove that. 

Please see my comment on the Chocolate Sans PR regarding the UFO format. Is there a way that the original designer can open / import the UFO in font creator and continue work? Otherwise, the UFO cannot be modified on my end.

**Comment by aaronbell** [comment]
Per the same discussion on Chocolate Sans – in discussing with my colleagues, it sounds like it would be best for us to maintain a separate fork of the font at this time with the source set up as a `UFO`. We'll let you know of any issues that we discover that we'd suggest fixing upstream, and can discuss if it makes sense to re-merge the repositories at a later point.

**Comment by hfhchan** [comment]
> Oh! I thought I'd read somewhere that this included glyphs from an Adobe project. I can remove that.

Yes, only Chocolate Sans uses glyphs from Source Han Sans. CatusSerif is using glyphs exported from GlyphWiki. All the glyphs that were exported from GlyphWiki were done by me and modified by @jisbig5 and @MoonlitOwen.

**Comment by hfhchan** [comment]
> Per the same discussion on Chocolate Sans – in discussing with my colleagues, it sounds like it would be best for us to maintain a separate fork of the font at this time with the source set up as a UFO. We'll let you know of any issues that we discover that we'd suggest fixing upstream, and can discuss if it makes sense to re-merge the repositories at a later point.

Sure, many thanks for your assistance.

**Comment by hfhchan** [comment]
@aaronbell do you have the full list of glyph changes that were made downstream? Is [this](https://github.com/google/fonts/pull/7665#issuecomment-2112192424) only it?

**Comment by hfhchan** [comment]
Also I'd like to know the process for updates -- if we have updated UFOs, do we update our repo and then make an issue on the google fonts repo?

**Pull request closed without merging**
